---
title: '2019-03-27'
author: "林茂廷"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(lubridate)
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```
```{r}
library(lubridate)
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
typeof(LisbonDateTime)
as.double(LisbonDateTime)
as.double(twDateTime)
```
```{r}
library(lubridate)
Japandatetime<-with_tz(twDateTime,tzone="Asia/japan")
Japandatetime
typeof(Japandatetime)
as.double(Japandatetime)
as.double(twDateTime)
```
```{r}
dtobject2 <- ymd("2018-09-11")
dtobject <- mdy_hms("03-14-2019 04:11:47")
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
a+b
a-b
a*b
a/b
```
```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
a+bL
aL+bL
class(a+bL)
class(aL+bL)
a-bL
aL-bL
class(a-bL)
class(aL-bL)
class(a*bL)
class(aL*bL)
```
```{r}
c <- 4

c+a
class(c+a)
```
```{r}
a^b
a %% b
class(a^b)
class(aL^bL)
```
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```
```{r}
startingDate<- ymd("2019-01-01")
startingDate + years(1)
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```
```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x3 == y3
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
x2
is.na(x2)
```
```{r}
x2
is.na(x2)
```
```{r}
0/0
```




